<?xml version="1.0" encoding="utf-8"?><Database Name="bookstore" Class="ModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=simpleblog.mssql.somee.com;Initial Catalog=simpleblog;Persist Security Info=True;User ID=tuanbuidev_SQLLogin_1" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="bookstoreConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Book" Member="Books">
    <Type Name="Book">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CateID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Detail" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ImagePath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Meta_Keyword" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Meta_Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ShowOnHome" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Category_Book" Member="Category" ThisKey="CateID" OtherKey="ID" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Detail" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ImagePath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Meta_Keyword" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Meta_Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ShowOnHome" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Category_Book" Member="Books" ThisKey="ID" OtherKey="CateID" Type="Book" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="ImagePath" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>